#!/bin/bash

################################################################################
# Claude Prompt Engine - Universal Installation Script
# Supports: Linux, macOS, Windows (Git Bash/WSL)
# Creates self-contained, production-ready installation
################################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="${INSTALL_DIR:-.}"
PROJECT_NAME="claude-prompt-engine"
MIN_NODE_VERSION="18"
MIN_NPM_VERSION="9"
PORT="${PORT:-3000}"
SKIP_KEYS="${SKIP_KEYS:-}"

echo -e "${BLUE}"
cat << "EOF"
╔══════════════════════════════════════════════════════════════════════════════╗
║            Claude Prompt Engine + iAI — Universal Installer v1.3            ║
╚══════════════════════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# ── Helpers ──────────────────────────────────────────────────────────────────
print_status()  { echo -e "${GREEN}✓${NC} $1"; }
print_error()   { echo -e "${RED}✗${NC} $1"; }
print_warning() { echo -e "${YELLOW}⚠${NC} $1"; }
print_info()    { echo -e "${BLUE}ℹ${NC} $1"; }

# ── Detect OS ─────────────────────────────────────────────────────────────────
detect_os() {
  OS="linux"
  case "$(uname -s)" in
    Darwin*)  OS="mac" ;;
    MINGW*|MSYS*|CYGWIN*) OS="windows" ;;
  esac
  print_info "Detected OS: $OS"
}

# ── Check Node.js ─────────────────────────────────────────────────────────────
check_nodejs() {
    print_info "Checking Node.js installation..."
    if ! command -v node &> /dev/null; then
        print_error "Node.js is not installed"
        echo ""
        echo "Install Node.js for your platform:"
        echo "  • macOS:         brew install node  (or https://nodejs.org)"
        echo "  • Ubuntu/Debian: sudo apt-get install nodejs npm"
        echo "  • RHEL/CentOS:   sudo dnf install nodejs npm"
        echo "  • Windows:       https://nodejs.org/en/download/"
        echo "  • All platforms: https://nodejs.org/en/download/package-manager/"
        exit 1
    fi
    
    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt "$MIN_NODE_VERSION" ]; then
        print_error "Node.js version $MIN_NODE_VERSION+ required (found v$NODE_VERSION)"
        exit 1
    fi
    
    print_status "Node.js $(node -v) installed"
}

# ── Check npm ─────────────────────────────────────────────────────────────────
check_npm() {
    print_info "Checking npm installation..."
    if ! command -v npm &> /dev/null; then
        print_error "npm is not installed"
        exit 1
    fi
    
    NPM_VERSION=$(npm -v | cut -d'.' -f1)
    if [ "$NPM_VERSION" -lt "$MIN_NPM_VERSION" ]; then
        print_error "npm version $MIN_NPM_VERSION+ required (found v$(npm -v))"
        exit 1
    fi
    
    print_status "npm $(npm -v) installed"
}

# ── Create project structure ──────────────────────────────────────────────────
create_structure() {
    print_info "Creating project structure..."
    
    cd "$INSTALL_DIR"
    
    mkdir -p core public/js public/css migrations test-data logs configs
    mkdir -p memory/iai/episodes
    
    print_status "Project structure created"
}

# ── Install npm dependencies ──────────────────────────────────────────────────
install_dependencies() {
    print_info "Installing npm dependencies..."
    print_warning "This may take 1-3 minutes..."
    
    if npm install --verbose 2>&1 | tail -10; then
        print_status "Dependencies installed successfully"
    else
        print_error "Failed to install dependencies — trying fallback..."
        npm install --no-optional --legacy-peer-deps
        print_status "Dependencies installed (legacy mode)"
    fi
}

# ── Generate config files ─────────────────────────────────────────────────────
generate_configs() {
    print_info "Generating configuration files..."
    
    if [ ! -f ".env" ]; then
        cat > .env << 'ENVEOF'
# Claude Prompt Engine — Environment Variables
# Generated by install.sh
# ⚠  NEVER commit this file to version control

# ── AI Engine ────────────────────────────────────────────────
# OpenAI API (primary iAI engine — requires billing credit)
# Generate: https://platform.openai.com/api-keys
OPENAI_API_KEY=

# GitHub Personal Access Token (Copilot fallback + GitHub API)
# Generate: https://github.com/settings/tokens/new
GH_TOKEN=

# ── Telephony (Optional) ─────────────────────────────────────
# Telnyx SIP/VoIP integration
# Generate: https://portal.telnyx.com/#/app/api-keys
TELNYX_API_KEY=

# ── Database ─────────────────────────────────────────────────
MYSQL_HOST=localhost
MYSQL_USER=root
MYSQL_PASS=
MYSQL_DB=vicidial

# ── App ──────────────────────────────────────────────────────
PORT=3000
NODE_ENV=development
DB_PATH=./prompt_engine.db
ENVEOF
        print_status ".env created — run 'npm run setup' to fill in your keys"
    else
        print_status ".env already exists — skipping"
    fi
    
    # Ensure .env is gitignored
    if [ -f ".gitignore" ]; then
        if ! grep -q '^\.env$' .gitignore; then
            echo ".env" >> .gitignore
            print_status ".env added to .gitignore"
        fi
    fi
    
    if [ ! -f "config.json" ]; then
        cat > config.json << 'CFGEOF'
{
  "port": 3000,
  "database": { "path": "./prompt_engine.db" },
  "api": { "maxBodySize": "1mb", "corsEnabled": true },
  "hardware": { "autoDetect": true, "forceTier": null },
  "validation": { "phoneMinDigits": 10, "checkDuplicates": true },
  "deployment": { "mode": "local", "environment": "development" },
  "logging": { "level": "info", "file": "./logs/app.log" }
}
CFGEOF
        print_status "config.json created"
    fi
}

# ── Create helper scripts ─────────────────────────────────────────────────────
create_scripts() {
    print_info "Creating convenience scripts..."
    
    cat > start.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting Claude Prompt Engine..."
npm start
EOF
    chmod +x start.sh

    cat > stop.sh << 'EOF'
#!/bin/bash
echo "⏹ Stopping Claude Prompt Engine..."
fuser -k 3000/tcp 2>/dev/null || pkill -f "node.*server.js" 2>/dev/null || true
echo "✓ Server stopped"
EOF
    chmod +x stop.sh

    chmod +x setup-keys.sh 2>/dev/null || true
    print_status "Helper scripts created"
}

# ── Test installation ─────────────────────────────────────────────────────────
test_installation() {
    print_info "Testing installation..."
    
    node -v &>/dev/null && print_status "Node.js OK" || { print_error "Node.js test failed"; exit 1; }
    npm -v  &>/dev/null && print_status "npm OK"     || { print_error "npm test failed";     exit 1; }
    [ -f "package.json" ] && print_status "package.json found" || { print_error "package.json missing"; exit 1; }
    [ -f "server.js" ]    && print_status "server.js found"    || { print_error "server.js missing";    exit 1; }
}

# ── Setup API keys (interactive, optional) ────────────────────────────────────
setup_keys_prompt() {
    if [ -n "$SKIP_KEYS" ]; then return; fi
    
    echo ""
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${YELLOW}  API Key Setup${NC}"
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "  iAI needs an AI API key to power its chat intelligence."
    echo ""
    echo "  You can set up keys now (interactive wizard) or later."
    echo "  Keys are needed from:"
    echo "    • OpenAI: https://platform.openai.com/api-keys  (primary)"
    echo "    • GitHub: https://github.com/settings/tokens/new (optional)"
    echo "    • Telnyx: https://portal.telnyx.com (optional, VoIP only)"
    echo ""
    
    printf "  Run the API key setup wizard now? (Y/n): "
    read -r RUN_SETUP
    
    if [[ ! "$RUN_SETUP" =~ ^[Nn]$ ]]; then
        bash setup-keys.sh
    else
        echo ""
        print_info "Skipped key setup. Run later:"
        echo "    npm run setup           # Interactive terminal wizard"
        echo "    npm start               # Start server, then visit /setup.html"
    fi
}

# ── Show completion instructions ──────────────────────────────────────────────
show_instructions() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                     Installation Complete! 🎉                               ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${GREEN}Quick Start:${NC}"
    echo ""
    echo "  1. Configure API keys (if not done):"
    echo "     npm run setup          ← Interactive terminal wizard"
    echo "     # OR start server, visit http://localhost:3000/setup.html"
    echo ""
    echo "  2. Start the server:"
    echo "     npm start"
    echo ""
    echo "  3. Open in browser:"
    echo "     http://localhost:$PORT            ← Main app"
    echo "     http://localhost:$PORT/iai.html   ← iAI assistant"
    echo "     http://localhost:$PORT/setup.html ← Key setup wizard"
    echo ""
    echo -e "${GREEN}Commands:${NC}"
    echo ""
    echo "  npm start          Start server"
    echo "  npm run setup      Configure API keys (terminal)"
    echo "  npm run setup:win  Configure API keys (Windows PowerShell)"
    echo "  npm test           Run test suite"
    echo ""
    echo -e "${GREEN}System:${NC}"
    echo "  Node.js $(node -v) | npm $(npm -v) | Port $PORT"
    echo ""
    echo -e "${BLUE}Repo: https://github.com/EDP1973/Claude_Prompt_Engine-v3.0${NC}"
    echo ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    print_info "System: $(uname -s)"
    print_info "User: $(whoami)"
    print_info "Directory: $(pwd)"
    echo ""
    
    detect_os
    check_nodejs
    check_npm
    create_structure
    install_dependencies
    generate_configs
    create_scripts
    test_installation
    show_instructions
    setup_keys_prompt
}

trap 'print_error "Installation failed at line $LINENO"; exit 1' ERR

main

print_status "Installation completed successfully!"

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
INSTALL_DIR="${INSTALL_DIR:-.}"
PROJECT_NAME="claude-prompt-engine"
MIN_NODE_VERSION="18"
MIN_NPM_VERSION="9"
PORT="${PORT:-3000}"

echo -e "${BLUE}"
cat << "EOF"
╔══════════════════════════════════════════════════════════════════════════════╗
║                   Claude Prompt Engine - Installation                        ║
║                          Universal Installer v1.0                           ║
╚══════════════════════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Function to print colored output
print_status() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Check if Node.js is installed
check_nodejs() {
    print_info "Checking Node.js installation..."
    if ! command -v node &> /dev/null; then
        print_error "Node.js is not installed"
        echo ""
        echo "Installation instructions:"
        echo "  • macOS: brew install node"
        echo "  • Ubuntu/Debian: sudo apt-get install nodejs npm"
        echo "  • Windows: Download from https://nodejs.org"
        echo "  • Official site: https://nodejs.org/en/download"
        exit 1
    fi
    
    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt "$MIN_NODE_VERSION" ]; then
        print_error "Node.js version $MIN_NODE_VERSION+ required (found v$NODE_VERSION)"
        exit 1
    fi
    
    print_status "Node.js $(node -v) installed"
}

# Check if npm is installed
check_npm() {
    print_info "Checking npm installation..."
    if ! command -v npm &> /dev/null; then
        print_error "npm is not installed"
        exit 1
    fi
    
    NPM_VERSION=$(npm -v | cut -d'.' -f1)
    if [ "$NPM_VERSION" -lt "$MIN_NPM_VERSION" ]; then
        print_error "npm version $MIN_NPM_VERSION+ required (found v$(npm -v))"
        exit 1
    fi
    
    print_status "npm $(npm -v) installed"
}

# Create project structure
create_structure() {
    print_info "Creating project structure..."
    
    cd "$INSTALL_DIR"
    
    # Create necessary directories
    mkdir -p core
    mkdir -p public/js/css
    mkdir -p migrations
    mkdir -p test-data
    mkdir -p logs
    mkdir -p configs
    mkdir -p memory/iai/episodes
    
    print_status "Project structure created"
}

# Install dependencies
install_dependencies() {
    print_info "Installing npm dependencies..."
    print_warning "This may take 2-3 minutes..."
    
    if npm install --verbose 2>&1 | tail -20; then
        print_status "Dependencies installed successfully"
    else
        print_error "Failed to install dependencies"
        print_info "Trying alternative installation method..."
        npm install --no-optional --legacy-peer-deps
        print_status "Dependencies installed (alternative method)"
    fi
}

# Create database
create_database() {
    print_info "Initializing database..."
    
    # Database will be auto-created on first server run
    print_status "Database initialization prepared"
}

# Generate config files
generate_configs() {
    print_info "Generating configuration files..."
    
    # Create .env file if it doesn't exist
    if [ ! -f ".env" ]; then
        cat > .env << EOF
# Claude Prompt Engine - Configuration
PORT=3000
NODE_ENV=development
DB_PATH=./prompt_engine.db
API_KEY=development-key-change-in-production
CORS_ORIGIN=http://localhost:3000
MAX_FILE_SIZE=104857600
FORCE_TIER=

# iAI — Intelligent Assistant
# Set GH_TOKEN to a GitHub personal access token with "Copilot Requests" scope
# Get one at: https://github.com/settings/tokens
GH_TOKEN=
# Set OPENAI_API_KEY to enable TTS voice output in iAI (optional)
OPENAI_API_KEY=
EOF
        print_status ".env configuration file created"
    fi
    
    # Create config.json if it doesn't exist
    if [ ! -f "config.json" ]; then
        cat > config.json << 'EOF'
{
  "port": 3000,
  "database": {
    "path": "./prompt_engine.db",
    "maxSize": 1000000000
  },
  "api": {
    "maxBodySize": "1mb",
    "corsEnabled": true,
    "corsOrigin": "http://localhost:3000"
  },
  "hardware": {
    "autoDetect": true,
    "forceTier": null
  },
  "validation": {
    "phoneMinDigits": 10,
    "phoneMaxDigits": 15,
    "checkDuplicates": true,
    "fileMaxSize": 104857600
  },
  "deployment": {
    "mode": "local",
    "environment": "development"
  },
  "logging": {
    "level": "info",
    "file": "./logs/app.log"
  }
}
EOF
        print_status "config.json created"
    fi
}

# Test installation
test_installation() {
    print_info "Testing installation..."
    
    # Test Node.js
    if node -v &> /dev/null; then
        print_status "Node.js test passed"
    else
        print_error "Node.js test failed"
        exit 1
    fi
    
    # Test npm
    if npm -v &> /dev/null; then
        print_status "npm $(npm -v) verified"
    else
        print_error "npm verification failed"
        exit 1
    fi
    
    # Test required files
    if [ -f "package.json" ]; then
        print_status "package.json found"
    else
        print_error "package.json not found"
        exit 1
    fi
    
    if [ -f "server.js" ]; then
        print_status "server.js found"
    else
        print_error "server.js not found"
        exit 1
    fi
}

# Create start scripts
create_scripts() {
    print_info "Creating convenience scripts..."
    
    # Create start script
    cat > start.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting Claude Prompt Engine..."
npm run web
EOF
    chmod +x start.sh
    print_status "start.sh created"
    
    # Create test script
    cat > test.sh << 'EOF'
#!/bin/bash
echo "🧪 Running tests..."
bash run-tests.sh
EOF
    chmod +x test.sh
    print_status "test.sh created"
    
    # Create stop script
    cat > stop.sh << 'EOF'
#!/bin/bash
echo "⏹ Stopping Claude Prompt Engine..."
pkill -f "node.*server.js"
echo "✓ Server stopped"
EOF
    chmod +x stop.sh
    print_status "stop.sh created"
}

# Display startup instructions
show_instructions() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║                     Installation Complete! 🎉                               ║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${GREEN}Quick Start:${NC}"
    echo ""
    echo "  1. Navigate to project directory:"
    echo "     cd $(pwd)"
    echo ""
    echo "  2. (Optional) Enable iAI assistant:"
    echo "     export GH_TOKEN=<github_token_with_copilot_scope>"
    echo "     export OPENAI_API_KEY=<openai_key>    # for voice output"
    echo "     Or add them to .env (already created)"
    echo ""
    echo "  3. Start the server:"
    echo "     npm run web"
    echo ""
    echo "  4. Open in browser:"
    echo "     http://localhost:3000"
    echo "     http://localhost:3000/iai.html  ← iAI assistant"
    echo ""
    echo -e "${GREEN}Useful Commands:${NC}"
    echo ""
    echo "  npm run web        - Start server"
    echo "  npm start          - Start server (alias)"
    echo "  npm run cli        - Run CLI interface"
    echo "  npm test           - Run test suite"
    echo "  bash run-tests.sh  - Run comprehensive tests"
    echo ""
    echo -e "${GREEN}First Steps:${NC}"
    echo ""
    echo "  1. Go to http://localhost:3000/iai.html"
    echo "     → Chat with iAI (set GH_TOKEN first for best results)"
    echo ""
    echo "  2. Go to http://localhost:3000/settings.html"
    echo "     → Configure hardware tier and deployment mode"
    echo ""
    echo "  3. Go to http://localhost:3000/data-import.html"
    echo "     → Import your first data file (CSV/Excel/TXT)"
    echo ""
    echo "  4. Go to http://localhost:3000/query-builder-form.html"
    echo "     → Build and test SQL queries"
    echo ""
    echo "  5. Go to http://localhost:3000/query-builder-visual.html"
    echo "     → Use visual query builder with drag-drop"
    echo ""
    echo -e "${GREEN}Documentation:${NC}"
    echo ""
    echo "  • Installation Guide: INSTALLATION_GUIDE.md"
    echo "  • User Manual:        USER_MANUAL.md"
    echo "  • Changelog:          CHANGELOG.md"
    echo "  • Contributing:       CONTRIBUTING.md"
    echo ""
    echo -e "${GREEN}System Information:${NC}"
    echo ""
    echo "  • Node.js: $(node -v)"
    echo "  • npm: $(npm -v)"
    echo "  • Port: $PORT"
    echo "  • Database: ./prompt_engine.db"
    echo "  • Installation: $(pwd)"
    echo ""
    echo -e "${BLUE}Need help? Visit: https://github.com/EDP1973/Claude_Prompt_Engine-v3.0${NC}"
    echo ""
}

# Main installation flow
main() {
    print_info "System: $(uname -s)"
    print_info "User: $(whoami)"
    print_info "Directory: $(pwd)"
    echo ""
    
    check_nodejs
    check_npm
    create_structure
    install_dependencies
    create_database
    generate_configs
    create_scripts
    test_installation
    show_instructions
}

# Error handling
trap 'print_error "Installation failed"; exit 1' ERR

# Run main installation
main

print_status "Installation completed successfully!"
